#title: Ramakrishnan Natarajan
#description: Design Portfolio
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: daattali/beautiful-jekyll@6.0.1
#author:
 # social:
  #  twitter: yourusername
   # github: yourusername
    #linkedin: yourusername
    #email: youremail@example.com
