###########################################################
#title: Ramakrishnan Natarajan
#description: Design Portfolio
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#remote_theme: daattali/beautiful-jekyll@6.0.1
#plugins:
 # - jekyll-remote-theme
 ###########################################################
remote_theme: beautiful-jekyll@6.0.1
title: Ramakrishnan Natarajan's Design Portfolio
author: Ramakrishnan Natarajan
social-network-links:
  email: "ramkrish2020@gmail.com"
  linkedin: natarajanramakrishnan
  github: rnmech
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
