###########################################################
title: Ramakrishnan Natarajan
description: Design Portfolio
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
linkedin_username: natarajanramakrishnan
email: ramkrish2020@gmail.com
resume: https://docs.google.com/viewer?url=https://raw.githubusercontent.com/rnmech/CAD/main/docs/Ramakrishnan_Git_Resume.pdf
###########################################################
