###########################################################
title: Ramakrishnan Natarajan
description: Design Portfolio
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
###########################################################
